# Loads default set of integrations. Do not remove.
default_config:

# Text to speech
tts:
  - platform: google_translate

homeassistant:
  packages: !include_dir_named packages/
  customize:
    sensor.outdoor_absolute_humidity:
      unit_of_measurement: "g/m³"

# Extend data logging
recorder:
  purge_keep_days: 20
  exclude:
    entities:
      - sensor.nodec_latitude
      - sensor.nodec_longitude
    entity_globs:
      - sensor.c3_alarm_*_adresse
      - sensor.c3_alarm_*_titel

# Tailscale
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
  ip_ban_enabled: true
  login_attempts_threshold: 5

# Statisk IP til Sonos højtalerer
sonos:
  media_player:
    hosts:
      - 192.168.1.192
      - 192.168.1.234

# Brændstofpriser
fuelprices_dk:
  companies:
    - "ok"
  fueltypes:
    - "oktan 95"
